version: '3.8'

services:
    app:
        build: .
        container_name: location_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - app_network

    db:
        image: mysql:8
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: location_case
            MYSQL_ROOT_PASSWORD: 123456
        ports:
            - "3306:3306"
        networks:
            - app_network

    nginx:
        image: nginx:latest
        container_name: location_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
